### ISSUE TITLE
Support for vectors

### ISSUE THREAD

**Issue by Makogan** [RLado/rsparse#5]
I think it would be useful to have support for algebraic vectors. For example when solving overly contained systems where A is a tall matrix one usually does `A^tAx = A^tb` to turn the system into a square one.

This is not easy to do with the current API. It would also be nice to construct matrices directly from std::vectors instead of nested vectors for efficiency reasons.

**Comment by RLado** [comment]
Thank you for your suggestion, however I am not sure I fully understand your request. 

Sparse matrices (`Sprs`) can be operated on using dense vectors (std::vec) by using the `gaxpy` function. Alternatively, you could also convert a dense vector to a sparse matrix (`Sprs`) but that would not be as efficient.

Regarding the construction of matrices from std::vectors I am not sure what you mean. Using a vector and placing its contents sequentially onto a matrix does not make sense to me for building a sparse matrix, as I would need more information to determine where those values are located. However, if what you are suggesting is to directly write your sparse matrix directly in proper CSC format you can already do so without creating any intermediate representations. You can define a sparse matrix 'A' as such:
```Rust
// Create a CSC sparse matrix A
let a = rsparse::data::Sprs{
    // Maximum number of entries
    nzmax: 5,
    // number of rows
    m: 3,
    // number of columns
    n: 3,
    // Values
    x: vec![1., 9., 9., 2., 9.],
    // Indices  
    i: vec![1, 2, 2, 0, 2],
    // Pointers
    p: vec![0, 2, 3, 5]
};
```
Which would be equivalent to this matrix:
```
[0, 0, 2]
[1, 0, 0]
[9, 9, 9]
```
(no nested std::vec required)
*Note that although this might seem cumbersome for the small example matrix large sparse matrices are much more efficiently represented this way*
