### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by MothNik** [RLado/rsparse#6]
Hello,

Thanks for providing this package! I want to write a Python wrapper for this since the support for sparse QR-decomposition in Python is relatively sparse itself.

I found that when one runs the linter `cargo clippy` on the project, there are more than 200 suggestions for improvements (mostly returns and the [`&mut Vec` typing](https://rust-lang.github.io/rust-clippy/master/index.html#/ptr_arg)).

I would like to help on this and contribute to the package since I also would like to contribute the feature to solve (multiple right hand sides) from an already computated factorization after this (I will open the feature request later).
Are you interested in this?

Kind regards

**Comment by RLado** [comment]
Hi!

Thank you for reaching out. You are right, there are a bunch of clippy suggestions I had ignored and would be nice to fix. If you are willing to contribute the changes I am all for improving the project. If I can help with anything please let me know.

Kind regards

**Comment by MothNik** [comment]
Hi-ho 👋 
I'm done and opened pull request #7  for the changes.

Kind regards

**Comment by MothNik** [comment]
Welcome! Since the PR is merged, I'll close this as completed.
